import 'package:http/http.dart' as http;

import '../model/post.dart';

class PostService {
  Future<Autogenerated> fetchPost() async {
    final response = await http.get(Uri.parse(
        "https://api.themoviedb.org/3/discover/movie?sort_by=popularity.desc&api_key=3fd2be6f0c70a2a598f084ddfb75487c&page=1/1"));

    if (response.statusCode == 200) {
      return AutogeneratedFromJson(response.body);
    } else {
      throw Exception("Postlar gelmedi abim");
    }
  }
}
